### ISSUE TITLE
Doesn't work native docker on Mac

### ISSUE THREAD

**Issue by reiz** [madebymany/pharod#2]
I have Docker installed natively on Mac. Using this version: 

```
Docker version 1.12.0, build 8eab29e, experimental
```

Then I execute `pharod-start` I always get the error message: 

```
To use Docker in OS X, you need to install Docker for Mac
or Dlite: https://github.com/nlf/dlite
```

Any ideas what's wrong?

**Comment by sebastian-julius** [comment]
We see the same issue. I simply added a `true ||` and fixed the host name inside the pharod-start script in line 15 and it worked. Tough that's quite some ugly patch. Any ideas, @dwb?

```
if true || pgrep -qx com.docker.backend; then
  echo "** Detected Docker for Mac"

  DOCKER_HOST_IP="localhost"
  # We have to hard-code this because we have no SSH access to the VM:
  DOCKER_FIRST_EPHEMERAL_PORT='32768'

elif command -v dlite >/dev/null; then
```

**Comment by d3v1an7** [comment]
@reiz @sebastian-julius let me know if this helps: #3

**Comment by sebastian-julius** [comment]
@d3v1an7 looking good to me 😄  👍  thanks

**Comment by zoltrain** [comment]
Hey @sebastian-julius @reiz @d3v1an7,

I think the default process name now is just "Docker". We were keeping support for dlite until the file system mounting was good enough in Docker for Mac, which for rails projects was woefully bad when it was first released.

Does anyone have need for dlite support? If not @dwb we could consider dropping support for dlite.

**Comment by dwb** [comment]
Sorry for being a bit sluggish on this! Just merged PRs by @d3v1an7 which should solve this 👍
